### ISSUE TITLE
Cannot find module './getAnswers'

### ISSUE THREAD

**Issue by talkingtab** [kgroat/create-electron-react-app#7]
`npx create-electron-react-app cera`

produces:
```
npx: installed 581 in 31.179s
Cannot find module './getAnswers'
```

**Comment by drewlong** [comment]
I'm seeing the same error. I installed with `npm i -g create-electron-react-app` .

**Comment by i0532386223** [comment]
➜  electron npx create-electron-react-app new-app
npx: installed 572 in 17.285s
Cannot find module './getAnswers'

➜  electron npm i -g create-electron-react-app
/usr/local/bin/create-electron-react-app -> /usr/local/lib/node_modules/create-electron-react-app/bin/create-electron-react-app
+ create-electron-react-app@1.2.1
added 572 packages from 738 contributors in 11.361s

➜  electron create-electron-react-app new-app
module.js:538
    throw err;
    ^
Error: Cannot find module './getAnswers'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-electron-react-app/src/index.js:3:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Can you advise anything?

**Comment by Laurian** [comment]
I downgraded to previus version and that one works 

```
npm uninstall create-electron-react-app -g  
npm install -g create-electron-react-app@v1.2.0
```

**Comment by milonti** [comment]
What's the actual issue causing it though? What am I missing if I downgrade?
